import { getDb } from "./db";
const COOKIE = "eventra_session";
async function hashToken(token){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function b64(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
export async function getSession(token){if(!token)return null;const h=await hashToken(token);const sql=getDb();const rows=await sql`SELECT s.id session_id,s.user_id,s.expires_at,u.email,u.display_name,COALESCE(array_agg(r.name) FILTER(WHERE r.name IS NOT NULL),ARRAY[]::text[]) roles FROM sessions s JOIN users u ON u.id=s.user_id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id WHERE s.token_hash=${h} AND s.revoked_at IS NULL AND s.expires_at>now() AND u.active=true GROUP BY s.id,u.id`;return rows[0]||null}
export async function createSession(userId){const raw=b64(crypto.getRandomValues(new Uint8Array(32)));const h=await hashToken(raw);await getDb()`INSERT INTO sessions(user_id,token_hash,expires_at) VALUES(${userId},${h},now()+interval '7 days')`;return raw}
export async function revokeSession(token){if(token)await getDb()`UPDATE sessions SET revoked_at=now() WHERE token_hash=${await hashToken(token)}`}
export async function hasPermission(session,permission){if(!session)return false;if(session.roles?.includes("admin"))return true;const rows=await getDb()`SELECT 1 FROM user_roles ur JOIN role_permissions rp ON rp.role_id=ur.role_id JOIN permissions p ON p.id=rp.permission_id WHERE ur.user_id=${session.user_id} AND p.name=${permission} LIMIT 1`;return !!rows[0]}
export function cookie(token,maxAge=604800){return COOKIE+"="+token+"; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age="+maxAge}
export { COOKIE as SESSION_COOKIE };